trigger:
- main

pool:
  name: Default

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore rubi_quiz4_dotnet.sln
  displayName: Restore dependencies

- script: dotnet build rubi_quiz4_dotnet.sln --configuration Release
  displayName: Build project